# Generated by Django 5.2.5 on 2025-08-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentresponse",
            name="selected_answer",
        ),
        migrations.RemoveField(
            model_name="studentresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="studentresponse",
            name="student",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="StudentResponse",
        ),
    ]
