# Generated by Django 5.2.5 on 2025-09-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_studentresponse_selected_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the quiz"
            ),
        ),
    ]
