# Generated by Django 5.2.5 on 2025-09-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_alter_question_text_alter_quiz_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="choice",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice (Single Answer)"),
                    ("checkbox", "Multiple Choice (Multiple Answers)"),
                    ("text", "Text Input"),
                    ("radio", "Radio Button"),
                ],
                default="mcq",
                max_length=20,
            ),
        ),
    ]
