# Generated by Django 5.2.5 on 2025-10-09 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_class_quiz_complete_by_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={},
        ),
        migrations.AddField(
            model_name="quiz",
            name="class_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="quiz.class",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="complete_by_date",
            field=models.DateTimeField(
                blank=True, help_text="Optional deadline for quiz completion", null=True
            ),
        ),
        migrations.DeleteModel(
            name="QuizAttempt",
        ),
    ]
